### ISSUE TITLE
Speed of detection

### ISSUE THREAD

**Issue by hoou** [coldKnight/TrafficLight_Detection-TensorFlowAPI#1]
Hi, first of all, thanks for sharing your code, you really helped me a lot. I have trained Faster RCNN and finally i got a success with testing. I just wanna ask, why detection in the first test image takes like 5-10 seconds and then every other takes only like 200ms? Do you have the same problem, or is it just me? I am just curious.

**Comment by JefferyGong** [comment]
@hoou I met the same situation. Maybe initialization needs some time at first running time.

**Comment by coldKnight** [comment]
@hoou you are right. I faced the same issues. The first image inference took a significantly more time than the others. @JefferyGong your explanation seems plausible as well. I will try my best to research and get back to you regarding this.

**Comment by coldKnight** [comment]
So one suggestion I received is that the initialization of the TensorFlow session takes some time. After the first time, this same TF session is reused. If you go to the console logs, you might be able to see this. I think this is the reason behind the longer inference times at the start. This is quite similar to what @JefferyGong suggested. 
I am closing this issue. Feel free to reopen it or add comments if you find more resources for the same. I would be happy to learn :slightly_smiling_face:
