### ISSUE TITLE
inference graph

### ISSUE THREAD

**Issue by onlyak** [coldKnight/TrafficLight_Detection-TensorFlowAPI#4]
can I get the drive link of the "frozen_models/frozen_sim_inception/frozen_inference_graph.pb"?

**Comment by coldKnight** [comment]
Hi,

You can find the pre-trained models from here: https://github.com/nhiddink/SDCND_Capstone_TEC

Simulator Model Weights: https://drive.google.com/open?id=0BzcEGp8MN5DiaGxsSkNlTEVVUVE
Real Data Model Weight: https://drive.google.com/open?id=0BzcEGp8MN5DiTVhoNmxQUU5ldms

**Comment by yiyichun** [comment]
Hi, @coldKnight ,
"Simulator Model Weights: https://drive.google.com/open?id=0BzcEGp8MN5DiaGxsSkNlTEVVUVE"
"Real Data Model Weight: https://drive.google.com/open?id=0BzcEGp8MN5DiTVhoNmxQUU5ldms"
I would like to ask the above model, which network is trained?
